server:
  port: 8082

spring:
  application:
    name: cloud_service_dao

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:8001/eureka

  instance:
    instance-id: springCloud-provider-dao-8082
    prefer-ip-address: true