name: Pull Request Flow
on:
  pull_request:
    branches:
      - 'feature**'
env:
  PROJECT_NAME: 1
jobs:
  pullRequest:
    runs-on: [ ubuntu-22.04 ]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3
        
      - name: Show Branch Info
        run: |
          git branch -v

      - name: Show Current Branch
        run: |
          echo ${{github.ref}}
        
