name: schedule work flow

on:
  schedule:
    - cron: '0/2 * * * *'
  workflow_dispatch:

jobs:
  bdba:
    runs-on: [ ubuntu-22.04 ]
    steps:
      - name: Setup 1
        run: |
          echo "1111"
