name: schedule work flow
on:
  schedule:
    - cron: '0/5 * * * *'
  workflow_run: 
    workflows: [feature-a]
    types:
      - completed
  workflow_dispatch:     
jobs:
  task:
    runs-on: [ ubuntu-22.04 ]
    steps:
      - name: Setup 1
        run: |
          echo "1111"
