name: schedule work flow
on:
  schedule:
    - cron: '0/5 * * * *'
  workflow_dispatch:
  workflow_run: 
    workflows: [feature-a-bdba]
    types:
      - completed
jobs:
  task:
    runs-on: [ ubuntu-22.04 ]
    steps:
      - name: Setup 1
        run: |
          echo ${{ github.ref_name }}
          
          echo ${{github.repository}}
          
          full_repository=${{github.repository}}
          echo $(full_repository)
          
          echo $($(echo $(full_repository) | cut -d '/' -f 2))
