name: schedule work flow
on:
  schedule:
    - cron: '0/5 * * * *'
  workflow_dispatch:
  workflow_run: 
    workflows: [feature-a-bdba]
    types:
      - completed
env:
  PROJECT_NAME: 1
jobs:
  task:
    runs-on: [ ubuntu-22.04 ]
    steps:
      - name: Setup 1
        run: |
          echo 分支名称
          echo ${{ github.ref_name }}
          echo 仓库名称
          echo ${{github.repository}}
          echo 11111
          FULL_REPOSITORY=${{github.repository}}
          echo ${FULL_REPOSITORY}
          
          repository=$(echo ${FULL_REPOSITORY} | cut -d '/' -f 1)
          echo 2222
          echo ${repository}
          echo 3333
          echo "PROJECT_NAME=$repository" >> $GITHUB_ENV
          echo ${{PROJECT_NAME}}
